// This file was autogenerated by ./vendors/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../javascripts/app.js', ['reAdoptAHydrant.Application'], ['reAdoptAHydrant.controllers.Map', 'reAdoptAHydrant.controllers.Panel', 'reAdoptAHydrant.services.HydrantService', 'reAdoptAHydrant.services.UserService']);
goog.addDependency('../../../../../javascripts/controllers/map_controller.js', ['reAdoptAHydrant.controllers.Map'], []);
goog.addDependency('../../../../../javascripts/controllers/panel_controller.js', ['reAdoptAHydrant.controllers.Panel'], []);
goog.addDependency('../../../../../javascripts/services/hydrant_service.js', ['reAdoptAHydrant.services.HydrantService'], []);
goog.addDependency('../../../../../javascripts/services/user_service.js', ['reAdoptAHydrant.services.UserService'], []);
